In [1]:
import numpy as np 

In [2]:
x = np.array([1,2,3])

In [3]:
print(type(x))

<class 'numpy.ndarray'>


In [4]:
print(x.shape)

(3,)


In [5]:
print(x[0],x[1],x[2])

1 2 3


In [6]:
x[1]=5

In [7]:
print(x)

[1 5 3]


In [8]:
y = np.array([[1,2,3],[4,5,6]])

In [9]:
print(y.shape)

(2, 3)


In [10]:
print(y[0,0],y[0,1],y[1,1],y[1,2])

1 2 5 6


In [11]:
z = np.zeros((2,2))

In [12]:
print(z)

[[0. 0.]
 [0. 0.]]


In [13]:
print(z)


[[0. 0.]
 [0. 0.]]


In [14]:
k = np.full((2,3),8)

In [16]:
print(k)

[[8 8 8]
 [8 8 8]]


In [17]:
k[1,1] = 9

In [18]:
print(k)

[[8 8 8]
 [8 9 8]]


In [19]:
e = np.random.random((2,2))
print(e)

[[0.78504404 0.95223473]
 [0.34064716 0.42932014]]


In [20]:
a = np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6]])

In [21]:
print(a)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


In [22]:
rw1 = a[:,1]
print(rw1,rw1.shape)

[2 3 4] (3,)


In [23]:
cl1 = a[:,1]
print(cl1, cl1.shape)

[2 3 4] (3,)


In [24]:
bo = np.array([[1,2],
               [3,4],
               [5,6]])

In [25]:

bool_idx = (bo > 2)

print(bool_idx)

print(bo[bool_idx])

print(bo[bo > 2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [26]:
bo = np.array([1,2])
print(bo.dtype)

bo = np.array([1.0, 2.0])
print(bo.dtype)

int64
float64


In [27]:
x = np.array([[1,2],
              [3,4]])

y = np.array([[3,4],
              [5,6]])

print(x + y)

print(x - y)

print(np.add(x, y))

print(np.sum(x))

print(np.sqrt(x))

print(x / y)

print(x * y)

print(np.multiply(x, y))

print(np.divide(x, y))

print(np.subtract(x, y))

[[ 4  6]
 [ 8 10]]
[[-2 -2]
 [-2 -2]]
[[ 4  6]
 [ 8 10]]
10
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[0.33333333 0.5       ]
 [0.6        0.66666667]]
[[ 3  8]
 [15 24]]
[[ 3  8]
 [15 24]]
[[0.33333333 0.5       ]
 [0.6        0.66666667]]
[[-2 -2]
 [-2 -2]]


In [28]:
x = np.array([[1,2],
              [3,4]])

y = np.array([[5,6],
              [7,8]])

v = np.array([9,10])

w = np.array([11,12])

# Inner product
print(v.dot(w))
print(np.dot(v, w))

print(x.dot(v))
print(np.dot(x, v))

print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [29]:
# -----------------------------------
# MATRIX TRANSPOSE
# -----------------------------------

x = np.array([[1,2],
              [3,4]])

print(x)

print(x.T)


[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [30]:
# -----------------------------------
# BROADCASTING
# -----------------------------------

x = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]])

v = np.array([1,0,1])

print(v + x)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [31]:
# -----------------------------------
# VECTOR MULTIPLICATION
# -----------------------------------

v = np.array([1,2])
w = np.array([4,5])

print(v * w)

# -----------------------------------
# RESHAPE
# -----------------------------------

v = np.array([1,2,3])
w = np.array([4,5])

print(np.reshape(v, (3,1)) * w)

[ 4 10]
[[ 4  5]
 [ 8 10]
 [12 15]]
